api_cohere = "omCqaJtdUKt8oEf3JfpPZxFwvxcaUywu1gAzFWKl" 
api_openai = "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"
